[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/archilab/Pairlink-library
    gilmaimon/ArduinoWebsockets@^0.5.4
    bblanchon/ArduinoJson@^7.2.2
    adafruit/Adafruit APDS9960 Library
    adafruit/Adafruit Unified Sensor@^1.1.15
    adafruit/Adafruit NeoPixel@^1.12.5
    madhephaestus/ESP32Servo@^3.0.8
    adafruit/Adafruit MPU6050
